// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contract.proto

package me.kay.proto;

public interface TransferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.Transfer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string owner_address = 1;</code>
   * @return The ownerAddress.
   */
  String getOwnerAddress();
  /**
   * <code>string owner_address = 1;</code>
   * @return The bytes for ownerAddress.
   */
  com.google.protobuf.ByteString
      getOwnerAddressBytes();

  /**
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();

  /**
   * <code>string to_address = 3;</code>
   * @return The toAddress.
   */
  String getToAddress();
  /**
   * <code>string to_address = 3;</code>
   * @return The bytes for toAddress.
   */
  com.google.protobuf.ByteString
      getToAddressBytes();
}
