// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Frame.proto

package me.kay.proto;

/**
 * Protobuf type {@code me.kay.proto.Transaction}
 */
public  final class Transaction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.kay.proto.Transaction)
    TransactionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Transaction.newBuilder() to construct.
  private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Transaction() {
    hash_ = "";
    type_ = 0;
    sign_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Transaction();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Transaction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            hash_ = s;
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 34: {
            me.kay.proto.Transfer.Builder subBuilder = null;
            if (contractCase_ == 4) {
              subBuilder = ((me.kay.proto.Transfer) contract_).toBuilder();
            }
            contract_ =
                input.readMessage(me.kay.proto.Transfer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((me.kay.proto.Transfer) contract_);
              contract_ = subBuilder.buildPartial();
            }
            contractCase_ = 4;
            break;
          }
          case 42: {
            me.kay.proto.CreateContract.Builder subBuilder = null;
            if (contractCase_ == 5) {
              subBuilder = ((me.kay.proto.CreateContract) contract_).toBuilder();
            }
            contract_ =
                input.readMessage(me.kay.proto.CreateContract.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((me.kay.proto.CreateContract) contract_);
              contract_ = subBuilder.buildPartial();
            }
            contractCase_ = 5;
            break;
          }
          case 50: {
            me.kay.proto.TriggerContract.Builder subBuilder = null;
            if (contractCase_ == 6) {
              subBuilder = ((me.kay.proto.TriggerContract) contract_).toBuilder();
            }
            contract_ =
                input.readMessage(me.kay.proto.TriggerContract.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((me.kay.proto.TriggerContract) contract_);
              contract_ = subBuilder.buildPartial();
            }
            contractCase_ = 6;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.kay.proto.Protocol.internal_static_me_kay_proto_Transaction_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.kay.proto.Protocol.internal_static_me_kay_proto_Transaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Transaction.class, Builder.class);
  }

  /**
   * Protobuf enum {@code me.kay.proto.Transaction.ContractType}
   */
  public enum ContractType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TransferType = 0;</code>
     */
    TransferType(0),
    /**
     * <code>CreateContractType = 1;</code>
     */
    CreateContractType(1),
    /**
     * <code>TriggerContractType = 2;</code>
     */
    TriggerContractType(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TransferType = 0;</code>
     */
    public static final int TransferType_VALUE = 0;
    /**
     * <code>CreateContractType = 1;</code>
     */
    public static final int CreateContractType_VALUE = 1;
    /**
     * <code>TriggerContractType = 2;</code>
     */
    public static final int TriggerContractType_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ContractType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ContractType forNumber(int value) {
      switch (value) {
        case 0: return TransferType;
        case 1: return CreateContractType;
        case 2: return TriggerContractType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContractType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ContractType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContractType>() {
            public ContractType findValueByNumber(int number) {
              return ContractType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Transaction.getDescriptor().getEnumTypes().get(0);
    }

    private static final ContractType[] VALUES = values();

    public static ContractType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ContractType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:me.kay.proto.Transaction.ContractType)
  }

  private int contractCase_ = 0;
  private Object contract_;
  public enum ContractCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    TRANSFER(4),
    CREATECONTRACT(5),
    TRIGGERCONTRACT(6),
    CONTRACT_NOT_SET(0);
    private final int value;
    private ContractCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ContractCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContractCase forNumber(int value) {
      switch (value) {
        case 4: return TRANSFER;
        case 5: return CREATECONTRACT;
        case 6: return TRIGGERCONTRACT;
        case 0: return CONTRACT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContractCase
  getContractCase() {
    return ContractCase.forNumber(
        contractCase_);
  }

  public static final int HASH_FIELD_NUMBER = 1;
  private volatile Object hash_;
  /**
   * <code>string hash = 1;</code>
   * @return The hash.
   */
  public String getHash() {
    Object ref = hash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      hash_ = s;
      return s;
    }
  }
  /**
   * <code>string hash = 1;</code>
   * @return The bytes for hash.
   */
  public com.google.protobuf.ByteString
      getHashBytes() {
    Object ref = hash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      hash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
   * @return The type.
   */
  public ContractType getType() {
    @SuppressWarnings("deprecation")
    ContractType result = ContractType.valueOf(type_);
    return result == null ? ContractType.UNRECOGNIZED : result;
  }

  public static final int TRANSFER_FIELD_NUMBER = 4;
  /**
   * <code>.me.kay.proto.Transfer transfer = 4;</code>
   * @return Whether the transfer field is set.
   */
  public boolean hasTransfer() {
    return contractCase_ == 4;
  }
  /**
   * <code>.me.kay.proto.Transfer transfer = 4;</code>
   * @return The transfer.
   */
  public me.kay.proto.Transfer getTransfer() {
    if (contractCase_ == 4) {
       return (me.kay.proto.Transfer) contract_;
    }
    return me.kay.proto.Transfer.getDefaultInstance();
  }
  /**
   * <code>.me.kay.proto.Transfer transfer = 4;</code>
   */
  public me.kay.proto.TransferOrBuilder getTransferOrBuilder() {
    if (contractCase_ == 4) {
       return (me.kay.proto.Transfer) contract_;
    }
    return me.kay.proto.Transfer.getDefaultInstance();
  }

  public static final int CREATECONTRACT_FIELD_NUMBER = 5;
  /**
   * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
   * @return Whether the createContract field is set.
   */
  public boolean hasCreateContract() {
    return contractCase_ == 5;
  }
  /**
   * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
   * @return The createContract.
   */
  public me.kay.proto.CreateContract getCreateContract() {
    if (contractCase_ == 5) {
       return (me.kay.proto.CreateContract) contract_;
    }
    return me.kay.proto.CreateContract.getDefaultInstance();
  }
  /**
   * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
   */
  public me.kay.proto.CreateContractOrBuilder getCreateContractOrBuilder() {
    if (contractCase_ == 5) {
       return (me.kay.proto.CreateContract) contract_;
    }
    return me.kay.proto.CreateContract.getDefaultInstance();
  }

  public static final int TRIGGERCONTRACT_FIELD_NUMBER = 6;
  /**
   * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
   * @return Whether the triggerContract field is set.
   */
  public boolean hasTriggerContract() {
    return contractCase_ == 6;
  }
  /**
   * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
   * @return The triggerContract.
   */
  public me.kay.proto.TriggerContract getTriggerContract() {
    if (contractCase_ == 6) {
       return (me.kay.proto.TriggerContract) contract_;
    }
    return me.kay.proto.TriggerContract.getDefaultInstance();
  }
  /**
   * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
   */
  public TriggerContractOrBuilder getTriggerContractOrBuilder() {
    if (contractCase_ == 6) {
       return (me.kay.proto.TriggerContract) contract_;
    }
    return me.kay.proto.TriggerContract.getDefaultInstance();
  }

  public static final int SIGN_FIELD_NUMBER = 7;
  private volatile Object sign_;
  /**
   * <code>string sign = 7;</code>
   * @return The sign.
   */
  public String getSign() {
    Object ref = sign_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>string sign = 7;</code>
   * @return The bytes for sign.
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    Object ref = sign_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hash_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (type_ != ContractType.TransferType.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (contractCase_ == 4) {
      output.writeMessage(4, (me.kay.proto.Transfer) contract_);
    }
    if (contractCase_ == 5) {
      output.writeMessage(5, (me.kay.proto.CreateContract) contract_);
    }
    if (contractCase_ == 6) {
      output.writeMessage(6, (me.kay.proto.TriggerContract) contract_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sign_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hash_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (type_ != ContractType.TransferType.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (contractCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (me.kay.proto.Transfer) contract_);
    }
    if (contractCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (me.kay.proto.CreateContract) contract_);
    }
    if (contractCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (me.kay.proto.TriggerContract) contract_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Transaction)) {
      return super.equals(obj);
    }
    Transaction other = (Transaction) obj;

    if (!getHash()
        .equals(other.getHash())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (type_ != other.type_) return false;
    if (!getSign()
        .equals(other.getSign())) return false;
    if (!getContractCase().equals(other.getContractCase())) return false;
    switch (contractCase_) {
      case 4:
        if (!getTransfer()
            .equals(other.getTransfer())) return false;
        break;
      case 5:
        if (!getCreateContract()
            .equals(other.getCreateContract())) return false;
        break;
      case 6:
        if (!getTriggerContract()
            .equals(other.getTriggerContract())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    switch (contractCase_) {
      case 4:
        hash = (37 * hash) + TRANSFER_FIELD_NUMBER;
        hash = (53 * hash) + getTransfer().hashCode();
        break;
      case 5:
        hash = (37 * hash) + CREATECONTRACT_FIELD_NUMBER;
        hash = (53 * hash) + getCreateContract().hashCode();
        break;
      case 6:
        hash = (37 * hash) + TRIGGERCONTRACT_FIELD_NUMBER;
        hash = (53 * hash) + getTriggerContract().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Transaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Transaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Transaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Transaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Transaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Transaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Transaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Transaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Transaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Transaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Transaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Transaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Transaction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.kay.proto.Transaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.kay.proto.Transaction)
      me.kay.proto.TransactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.kay.proto.Protocol.internal_static_me_kay_proto_Transaction_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.kay.proto.Protocol.internal_static_me_kay_proto_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transaction.class, Builder.class);
    }

    // Construct using me.kay.proto.Transaction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      hash_ = "";

      timestamp_ = 0L;

      type_ = 0;

      sign_ = "";

      contractCase_ = 0;
      contract_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.kay.proto.Protocol.internal_static_me_kay_proto_Transaction_descriptor;
    }

    @Override
    public Transaction getDefaultInstanceForType() {
      return Transaction.getDefaultInstance();
    }

    @Override
    public Transaction build() {
      Transaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Transaction buildPartial() {
      Transaction result = new Transaction(this);
      result.hash_ = hash_;
      result.timestamp_ = timestamp_;
      result.type_ = type_;
      if (contractCase_ == 4) {
        if (transferBuilder_ == null) {
          result.contract_ = contract_;
        } else {
          result.contract_ = transferBuilder_.build();
        }
      }
      if (contractCase_ == 5) {
        if (createContractBuilder_ == null) {
          result.contract_ = contract_;
        } else {
          result.contract_ = createContractBuilder_.build();
        }
      }
      if (contractCase_ == 6) {
        if (triggerContractBuilder_ == null) {
          result.contract_ = contract_;
        } else {
          result.contract_ = triggerContractBuilder_.build();
        }
      }
      result.sign_ = sign_;
      result.contractCase_ = contractCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Transaction) {
        return mergeFrom((Transaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Transaction other) {
      if (other == Transaction.getDefaultInstance()) return this;
      if (!other.getHash().isEmpty()) {
        hash_ = other.hash_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      switch (other.getContractCase()) {
        case TRANSFER: {
          mergeTransfer(other.getTransfer());
          break;
        }
        case CREATECONTRACT: {
          mergeCreateContract(other.getCreateContract());
          break;
        }
        case TRIGGERCONTRACT: {
          mergeTriggerContract(other.getTriggerContract());
          break;
        }
        case CONTRACT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Transaction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Transaction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int contractCase_ = 0;
    private Object contract_;
    public ContractCase
        getContractCase() {
      return ContractCase.forNumber(
          contractCase_);
    }

    public Builder clearContract() {
      contractCase_ = 0;
      contract_ = null;
      onChanged();
      return this;
    }


    private Object hash_ = "";
    /**
     * <code>string hash = 1;</code>
     * @return The hash.
     */
    public String getHash() {
      Object ref = hash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string hash = 1;</code>
     * @return The bytes for hash.
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hash = 1;</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      hash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {

      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 1;</code>
     * @param value The bytes for hash to set.
     * @return This builder for chaining.
     */
    public Builder setHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      hash_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
     * @return The type.
     */
    public ContractType getType() {
      @SuppressWarnings("deprecation")
      ContractType result = ContractType.valueOf(type_);
      return result == null ? ContractType.UNRECOGNIZED : result;
    }
    /**
     * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(ContractType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.me.kay.proto.Transaction.ContractType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.Transfer, me.kay.proto.Transfer.Builder, me.kay.proto.TransferOrBuilder> transferBuilder_;
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     * @return Whether the transfer field is set.
     */
    public boolean hasTransfer() {
      return contractCase_ == 4;
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     * @return The transfer.
     */
    public me.kay.proto.Transfer getTransfer() {
      if (transferBuilder_ == null) {
        if (contractCase_ == 4) {
          return (me.kay.proto.Transfer) contract_;
        }
        return me.kay.proto.Transfer.getDefaultInstance();
      } else {
        if (contractCase_ == 4) {
          return transferBuilder_.getMessage();
        }
        return me.kay.proto.Transfer.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public Builder setTransfer(me.kay.proto.Transfer value) {
      if (transferBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contract_ = value;
        onChanged();
      } else {
        transferBuilder_.setMessage(value);
      }
      contractCase_ = 4;
      return this;
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public Builder setTransfer(
        me.kay.proto.Transfer.Builder builderForValue) {
      if (transferBuilder_ == null) {
        contract_ = builderForValue.build();
        onChanged();
      } else {
        transferBuilder_.setMessage(builderForValue.build());
      }
      contractCase_ = 4;
      return this;
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public Builder mergeTransfer(me.kay.proto.Transfer value) {
      if (transferBuilder_ == null) {
        if (contractCase_ == 4 &&
            contract_ != me.kay.proto.Transfer.getDefaultInstance()) {
          contract_ = me.kay.proto.Transfer.newBuilder((me.kay.proto.Transfer) contract_)
              .mergeFrom(value).buildPartial();
        } else {
          contract_ = value;
        }
        onChanged();
      } else {
        if (contractCase_ == 4) {
          transferBuilder_.mergeFrom(value);
        }
        transferBuilder_.setMessage(value);
      }
      contractCase_ = 4;
      return this;
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public Builder clearTransfer() {
      if (transferBuilder_ == null) {
        if (contractCase_ == 4) {
          contractCase_ = 0;
          contract_ = null;
          onChanged();
        }
      } else {
        if (contractCase_ == 4) {
          contractCase_ = 0;
          contract_ = null;
        }
        transferBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public me.kay.proto.Transfer.Builder getTransferBuilder() {
      return getTransferFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    public me.kay.proto.TransferOrBuilder getTransferOrBuilder() {
      if ((contractCase_ == 4) && (transferBuilder_ != null)) {
        return transferBuilder_.getMessageOrBuilder();
      } else {
        if (contractCase_ == 4) {
          return (me.kay.proto.Transfer) contract_;
        }
        return me.kay.proto.Transfer.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.Transfer transfer = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.Transfer, me.kay.proto.Transfer.Builder, me.kay.proto.TransferOrBuilder>
        getTransferFieldBuilder() {
      if (transferBuilder_ == null) {
        if (!(contractCase_ == 4)) {
          contract_ = me.kay.proto.Transfer.getDefaultInstance();
        }
        transferBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.kay.proto.Transfer, me.kay.proto.Transfer.Builder, me.kay.proto.TransferOrBuilder>(
                (me.kay.proto.Transfer) contract_,
                getParentForChildren(),
                isClean());
        contract_ = null;
      }
      contractCase_ = 4;
      onChanged();;
      return transferBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.CreateContract, me.kay.proto.CreateContract.Builder, me.kay.proto.CreateContractOrBuilder> createContractBuilder_;
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     * @return Whether the createContract field is set.
     */
    public boolean hasCreateContract() {
      return contractCase_ == 5;
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     * @return The createContract.
     */
    public me.kay.proto.CreateContract getCreateContract() {
      if (createContractBuilder_ == null) {
        if (contractCase_ == 5) {
          return (me.kay.proto.CreateContract) contract_;
        }
        return me.kay.proto.CreateContract.getDefaultInstance();
      } else {
        if (contractCase_ == 5) {
          return createContractBuilder_.getMessage();
        }
        return me.kay.proto.CreateContract.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public Builder setCreateContract(me.kay.proto.CreateContract value) {
      if (createContractBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contract_ = value;
        onChanged();
      } else {
        createContractBuilder_.setMessage(value);
      }
      contractCase_ = 5;
      return this;
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public Builder setCreateContract(
        me.kay.proto.CreateContract.Builder builderForValue) {
      if (createContractBuilder_ == null) {
        contract_ = builderForValue.build();
        onChanged();
      } else {
        createContractBuilder_.setMessage(builderForValue.build());
      }
      contractCase_ = 5;
      return this;
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public Builder mergeCreateContract(me.kay.proto.CreateContract value) {
      if (createContractBuilder_ == null) {
        if (contractCase_ == 5 &&
            contract_ != me.kay.proto.CreateContract.getDefaultInstance()) {
          contract_ = me.kay.proto.CreateContract.newBuilder((me.kay.proto.CreateContract) contract_)
              .mergeFrom(value).buildPartial();
        } else {
          contract_ = value;
        }
        onChanged();
      } else {
        if (contractCase_ == 5) {
          createContractBuilder_.mergeFrom(value);
        }
        createContractBuilder_.setMessage(value);
      }
      contractCase_ = 5;
      return this;
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public Builder clearCreateContract() {
      if (createContractBuilder_ == null) {
        if (contractCase_ == 5) {
          contractCase_ = 0;
          contract_ = null;
          onChanged();
        }
      } else {
        if (contractCase_ == 5) {
          contractCase_ = 0;
          contract_ = null;
        }
        createContractBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public me.kay.proto.CreateContract.Builder getCreateContractBuilder() {
      return getCreateContractFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    public me.kay.proto.CreateContractOrBuilder getCreateContractOrBuilder() {
      if ((contractCase_ == 5) && (createContractBuilder_ != null)) {
        return createContractBuilder_.getMessageOrBuilder();
      } else {
        if (contractCase_ == 5) {
          return (me.kay.proto.CreateContract) contract_;
        }
        return me.kay.proto.CreateContract.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.CreateContract CreateContract = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.CreateContract, me.kay.proto.CreateContract.Builder, me.kay.proto.CreateContractOrBuilder>
        getCreateContractFieldBuilder() {
      if (createContractBuilder_ == null) {
        if (!(contractCase_ == 5)) {
          contract_ = me.kay.proto.CreateContract.getDefaultInstance();
        }
        createContractBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.kay.proto.CreateContract, me.kay.proto.CreateContract.Builder, me.kay.proto.CreateContractOrBuilder>(
                (me.kay.proto.CreateContract) contract_,
                getParentForChildren(),
                isClean());
        contract_ = null;
      }
      contractCase_ = 5;
      onChanged();;
      return createContractBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.TriggerContract, me.kay.proto.TriggerContract.Builder, TriggerContractOrBuilder> triggerContractBuilder_;
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     * @return Whether the triggerContract field is set.
     */
    public boolean hasTriggerContract() {
      return contractCase_ == 6;
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     * @return The triggerContract.
     */
    public me.kay.proto.TriggerContract getTriggerContract() {
      if (triggerContractBuilder_ == null) {
        if (contractCase_ == 6) {
          return (me.kay.proto.TriggerContract) contract_;
        }
        return me.kay.proto.TriggerContract.getDefaultInstance();
      } else {
        if (contractCase_ == 6) {
          return triggerContractBuilder_.getMessage();
        }
        return me.kay.proto.TriggerContract.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public Builder setTriggerContract(me.kay.proto.TriggerContract value) {
      if (triggerContractBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contract_ = value;
        onChanged();
      } else {
        triggerContractBuilder_.setMessage(value);
      }
      contractCase_ = 6;
      return this;
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public Builder setTriggerContract(
        me.kay.proto.TriggerContract.Builder builderForValue) {
      if (triggerContractBuilder_ == null) {
        contract_ = builderForValue.build();
        onChanged();
      } else {
        triggerContractBuilder_.setMessage(builderForValue.build());
      }
      contractCase_ = 6;
      return this;
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public Builder mergeTriggerContract(me.kay.proto.TriggerContract value) {
      if (triggerContractBuilder_ == null) {
        if (contractCase_ == 6 &&
            contract_ != me.kay.proto.TriggerContract.getDefaultInstance()) {
          contract_ = me.kay.proto.TriggerContract.newBuilder((me.kay.proto.TriggerContract) contract_)
              .mergeFrom(value).buildPartial();
        } else {
          contract_ = value;
        }
        onChanged();
      } else {
        if (contractCase_ == 6) {
          triggerContractBuilder_.mergeFrom(value);
        }
        triggerContractBuilder_.setMessage(value);
      }
      contractCase_ = 6;
      return this;
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public Builder clearTriggerContract() {
      if (triggerContractBuilder_ == null) {
        if (contractCase_ == 6) {
          contractCase_ = 0;
          contract_ = null;
          onChanged();
        }
      } else {
        if (contractCase_ == 6) {
          contractCase_ = 0;
          contract_ = null;
        }
        triggerContractBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public me.kay.proto.TriggerContract.Builder getTriggerContractBuilder() {
      return getTriggerContractFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    public TriggerContractOrBuilder getTriggerContractOrBuilder() {
      if ((contractCase_ == 6) && (triggerContractBuilder_ != null)) {
        return triggerContractBuilder_.getMessageOrBuilder();
      } else {
        if (contractCase_ == 6) {
          return (me.kay.proto.TriggerContract) contract_;
        }
        return me.kay.proto.TriggerContract.getDefaultInstance();
      }
    }
    /**
     * <code>.me.kay.proto.TriggerContract TriggerContract = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.kay.proto.TriggerContract, me.kay.proto.TriggerContract.Builder, TriggerContractOrBuilder>
        getTriggerContractFieldBuilder() {
      if (triggerContractBuilder_ == null) {
        if (!(contractCase_ == 6)) {
          contract_ = me.kay.proto.TriggerContract.getDefaultInstance();
        }
        triggerContractBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.kay.proto.TriggerContract, me.kay.proto.TriggerContract.Builder, TriggerContractOrBuilder>(
                (me.kay.proto.TriggerContract) contract_,
                getParentForChildren(),
                isClean());
        contract_ = null;
      }
      contractCase_ = 6;
      onChanged();;
      return triggerContractBuilder_;
    }

    private Object sign_ = "";
    /**
     * <code>string sign = 7;</code>
     * @return The sign.
     */
    public String getSign() {
      Object ref = sign_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sign = 7;</code>
     * @return The bytes for sign.
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign = 7;</code>
     * @param value The sign to set.
     * @return This builder for chaining.
     */
    public Builder setSign(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSign() {

      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 7;</code>
     * @param value The bytes for sign to set.
     * @return This builder for chaining.
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sign_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.kay.proto.Transaction)
  }

  // @@protoc_insertion_point(class_scope:me.kay.proto.Transaction)
  private static final Transaction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Transaction();
  }

  public static Transaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transaction>
      PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
    @Override
    public Transaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Transaction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Transaction> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Transaction> getParserForType() {
    return PARSER;
  }

  @Override
  public Transaction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

