// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contract.proto

package me.kay.proto;

public interface TriggerContractOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.kay.proto.TriggerContract)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string owner_address = 1;</code>
   * @return The ownerAddress.
   */
  String getOwnerAddress();
  /**
   * <code>string owner_address = 1;</code>
   * @return The bytes for ownerAddress.
   */
  com.google.protobuf.ByteString
      getOwnerAddressBytes();

  /**
   * <code>string contract_address = 2;</code>
   * @return The contractAddress.
   */
  String getContractAddress();
  /**
   * <code>string contract_address = 2;</code>
   * @return The bytes for contractAddress.
   */
  com.google.protobuf.ByteString
      getContractAddressBytes();

  /**
   * <code>string contract_params = 3;</code>
   * @return The contractParams.
   */
  String getContractParams();
  /**
   * <code>string contract_params = 3;</code>
   * @return The bytes for contractParams.
   */
  com.google.protobuf.ByteString
      getContractParamsBytes();
}
