// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contract.proto

package me.kay.proto;

/**
 * Protobuf type {@code me.kay.proto.TriggerContract}
 */
public  final class TriggerContract extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.kay.proto.TriggerContract)
    TriggerContractOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TriggerContract.newBuilder() to construct.
  private TriggerContract(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TriggerContract() {
    ownerAddress_ = "";
    contractAddress_ = "";
    contractParams_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TriggerContract();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TriggerContract(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            ownerAddress_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            contractAddress_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            contractParams_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.kay.proto.Contract.internal_static_me_kay_proto_TriggerContract_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.kay.proto.Contract.internal_static_me_kay_proto_TriggerContract_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TriggerContract.class, Builder.class);
  }

  public static final int OWNER_ADDRESS_FIELD_NUMBER = 1;
  private volatile Object ownerAddress_;
  /**
   * <code>string owner_address = 1;</code>
   * @return The ownerAddress.
   */
  public String getOwnerAddress() {
    Object ref = ownerAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ownerAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_address = 1;</code>
   * @return The bytes for ownerAddress.
   */
  public com.google.protobuf.ByteString
      getOwnerAddressBytes() {
    Object ref = ownerAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ownerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_ADDRESS_FIELD_NUMBER = 2;
  private volatile Object contractAddress_;
  /**
   * <code>string contract_address = 2;</code>
   * @return The contractAddress.
   */
  public String getContractAddress() {
    Object ref = contractAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      contractAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_address = 2;</code>
   * @return The bytes for contractAddress.
   */
  public com.google.protobuf.ByteString
      getContractAddressBytes() {
    Object ref = contractAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      contractAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_PARAMS_FIELD_NUMBER = 3;
  private volatile Object contractParams_;
  /**
   * <code>string contract_params = 3;</code>
   * @return The contractParams.
   */
  public String getContractParams() {
    Object ref = contractParams_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      contractParams_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_params = 3;</code>
   * @return The bytes for contractParams.
   */
  public com.google.protobuf.ByteString
      getContractParamsBytes() {
    Object ref = contractParams_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      contractParams_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOwnerAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ownerAddress_);
    }
    if (!getContractAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractAddress_);
    }
    if (!getContractParamsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contractParams_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOwnerAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ownerAddress_);
    }
    if (!getContractAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractAddress_);
    }
    if (!getContractParamsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contractParams_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TriggerContract)) {
      return super.equals(obj);
    }
    TriggerContract other = (TriggerContract) obj;

    if (!getOwnerAddress()
        .equals(other.getOwnerAddress())) return false;
    if (!getContractAddress()
        .equals(other.getContractAddress())) return false;
    if (!getContractParams()
        .equals(other.getContractParams())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerAddress().hashCode();
    hash = (37 * hash) + CONTRACT_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getContractAddress().hashCode();
    hash = (37 * hash) + CONTRACT_PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getContractParams().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TriggerContract parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TriggerContract parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TriggerContract parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TriggerContract parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TriggerContract parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TriggerContract parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TriggerContract parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TriggerContract parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TriggerContract parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TriggerContract parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TriggerContract parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TriggerContract parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TriggerContract prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.kay.proto.TriggerContract}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.kay.proto.TriggerContract)
      TriggerContractOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.kay.proto.Contract.internal_static_me_kay_proto_TriggerContract_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.kay.proto.Contract.internal_static_me_kay_proto_TriggerContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TriggerContract.class, Builder.class);
    }

    // Construct using me.kay.proto.TriggerContract.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      ownerAddress_ = "";

      contractAddress_ = "";

      contractParams_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.kay.proto.Contract.internal_static_me_kay_proto_TriggerContract_descriptor;
    }

    @Override
    public TriggerContract getDefaultInstanceForType() {
      return TriggerContract.getDefaultInstance();
    }

    @Override
    public TriggerContract build() {
      TriggerContract result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TriggerContract buildPartial() {
      TriggerContract result = new TriggerContract(this);
      result.ownerAddress_ = ownerAddress_;
      result.contractAddress_ = contractAddress_;
      result.contractParams_ = contractParams_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TriggerContract) {
        return mergeFrom((TriggerContract)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TriggerContract other) {
      if (other == TriggerContract.getDefaultInstance()) return this;
      if (!other.getOwnerAddress().isEmpty()) {
        ownerAddress_ = other.ownerAddress_;
        onChanged();
      }
      if (!other.getContractAddress().isEmpty()) {
        contractAddress_ = other.contractAddress_;
        onChanged();
      }
      if (!other.getContractParams().isEmpty()) {
        contractParams_ = other.contractParams_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TriggerContract parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TriggerContract) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object ownerAddress_ = "";
    /**
     * <code>string owner_address = 1;</code>
     * @return The ownerAddress.
     */
    public String getOwnerAddress() {
      Object ref = ownerAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ownerAddress_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string owner_address = 1;</code>
     * @return The bytes for ownerAddress.
     */
    public com.google.protobuf.ByteString
        getOwnerAddressBytes() {
      Object ref = ownerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ownerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_address = 1;</code>
     * @param value The ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      ownerAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerAddress() {

      ownerAddress_ = getDefaultInstance().getOwnerAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_address = 1;</code>
     * @param value The bytes for ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      ownerAddress_ = value;
      onChanged();
      return this;
    }

    private Object contractAddress_ = "";
    /**
     * <code>string contract_address = 2;</code>
     * @return The contractAddress.
     */
    public String getContractAddress() {
      Object ref = contractAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        contractAddress_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string contract_address = 2;</code>
     * @return The bytes for contractAddress.
     */
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      Object ref = contractAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_address = 2;</code>
     * @param value The contractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setContractAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      contractAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAddress() {

      contractAddress_ = getDefaultInstance().getContractAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string contract_address = 2;</code>
     * @param value The bytes for contractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setContractAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      contractAddress_ = value;
      onChanged();
      return this;
    }

    private Object contractParams_ = "";
    /**
     * <code>string contract_params = 3;</code>
     * @return The contractParams.
     */
    public String getContractParams() {
      Object ref = contractParams_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        contractParams_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string contract_params = 3;</code>
     * @return The bytes for contractParams.
     */
    public com.google.protobuf.ByteString
        getContractParamsBytes() {
      Object ref = contractParams_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        contractParams_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_params = 3;</code>
     * @param value The contractParams to set.
     * @return This builder for chaining.
     */
    public Builder setContractParams(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      contractParams_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_params = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractParams() {

      contractParams_ = getDefaultInstance().getContractParams();
      onChanged();
      return this;
    }
    /**
     * <code>string contract_params = 3;</code>
     * @param value The bytes for contractParams to set.
     * @return This builder for chaining.
     */
    public Builder setContractParamsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      contractParams_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.kay.proto.TriggerContract)
  }

  // @@protoc_insertion_point(class_scope:me.kay.proto.TriggerContract)
  private static final TriggerContract DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TriggerContract();
  }

  public static TriggerContract getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TriggerContract>
      PARSER = new com.google.protobuf.AbstractParser<TriggerContract>() {
    @Override
    public TriggerContract parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TriggerContract(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TriggerContract> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TriggerContract> getParserForType() {
    return PARSER;
  }

  @Override
  public TriggerContract getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

